#############################################################################
# Makefile for building: cheMVP.app/Contents/MacOS/cheMVP
# Generated by qmake (2.01a) (Qt 4.4.0) on: Mon Jul 28 14:58:05 2008
# Project:  cheMVP.pro
# Template: app
# Command: /usr/bin/qmake -macx -o cheMVP.xcodeproj/project.pbxproj cheMVP.pro
#############################################################################

QMAKE    = /usr/bin/qmake
cheMVP.xcodeproj/project.pbxproj: cheMVP.pro  /usr/local/Qt4.4/mkspecs/macx-xcode/qmake.conf /usr/local/Qt4.4/mkspecs/common/unix.conf \
		/usr/local/Qt4.4/mkspecs/common/mac.conf \
		/usr/local/Qt4.4/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.4/mkspecs/qconfig.pri \
		/usr/local/Qt4.4/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.4/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.4/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.4/mkspecs/features/debug.prf \
		/usr/local/Qt4.4/mkspecs/features/default_post.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.4/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.4/mkspecs/features/qt.prf \
		/usr/local/Qt4.4/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.4/mkspecs/features/moc.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.4/mkspecs/features/resources.prf \
		/usr/local/Qt4.4/mkspecs/features/uic.prf \
		/usr/local/Qt4.4/mkspecs/features/yacc.prf \
		/usr/local/Qt4.4/mkspecs/features/lex.prf \
		/Library/Frameworks/QtSvg.framework/QtSvg.prl \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -macx -o cheMVP.xcodeproj/project.pbxproj cheMVP.pro
/usr/local/Qt4.4/mkspecs/common/unix.conf:
/usr/local/Qt4.4/mkspecs/common/mac.conf:
/usr/local/Qt4.4/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.4/mkspecs/qconfig.pri:
/usr/local/Qt4.4/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.4/mkspecs/features/qt_config.prf:
/usr/local/Qt4.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.4/mkspecs/features/default_pre.prf:
/usr/local/Qt4.4/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.4/mkspecs/features/debug.prf:
/usr/local/Qt4.4/mkspecs/features/default_post.prf:
/usr/local/Qt4.4/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.4/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.4/mkspecs/features/warn_on.prf:
/usr/local/Qt4.4/mkspecs/features/qt.prf:
/usr/local/Qt4.4/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.4/mkspecs/features/moc.prf:
/usr/local/Qt4.4/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.4/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.4/mkspecs/features/resources.prf:
/usr/local/Qt4.4/mkspecs/features/uic.prf:
/usr/local/Qt4.4/mkspecs/features/yacc.prf:
/usr/local/Qt4.4/mkspecs/features/lex.prf:
/Library/Frameworks/QtSvg.framework/QtSvg.prl:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -macx -o cheMVP.xcodeproj/project.pbxproj cheMVP.pro

