#############################################################################
# Makefile for building: cheMVP.app/Contents/MacOS/cheMVP
# Generated by qmake (2.01a) (Qt 4.4.0) on: Mon Jul 28 14:58:05 2008
# Project:  cheMVP.pro
# Template: app
# Command: /usr/bin/qmake -macx -o cheMVP.xcodeproj/project.pbxproj cheMVP.pro
#############################################################################

MOC       = /Developer/Tools/Qt/moc
UIC       = /Developer/Tools/Qt/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_SVG_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
INCPATH       = -I/usr/local/Qt4.4/mkspecs/macx-xcode -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/Library/Frameworks/QtSvg.framework/Versions/4/Headers -I/usr/include/QtSvg -I/usr/include -I. -I. -I/usr/local/include -I/System/Library/Frameworks/CarbonCore.framework/Headers
DEL_FILE  = rm -f
MOVE      = mv -f

IMAGES = 
PARSERS =
preprocess: $(PARSERS) compilers
clean preprocess_clean: parser_clean compiler_clean

parser_clean:
mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compilers: ./moc_drawingcanvas.cpp ./moc_label.cpp ./moc_mainwindow.cpp ./qrc_chemvp.cpp
compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_drawingcanvas.cpp moc_label.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_drawingcanvas.cpp moc_label.cpp moc_mainwindow.cpp
moc_drawingcanvas.cpp: ../src/atom.h \
		../src/error.h \
		../src/defines.h \
		../src/drawinginfo.h \
		../src/bond.h \
		../src/label.h \
		../src/angle.h \
		../src/anglemarker.h \
		../src/arrow.h \
		../src/fileparser.h \
		../src/molecule.h \
		../src/drawingcanvas.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../src/drawingcanvas.h -o moc_drawingcanvas.cpp

moc_label.cpp: ../src/defines.h \
		../src/drawinginfo.h \
		../src/label.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../src/label.h -o moc_label.cpp

moc_mainwindow.cpp: ../src/drawingcanvas.h \
		../src/atom.h \
		../src/error.h \
		../src/defines.h \
		../src/drawinginfo.h \
		../src/bond.h \
		../src/label.h \
		../src/angle.h \
		../src/anglemarker.h \
		../src/arrow.h \
		../src/fileparser.h \
		../src/molecule.h \
		../src/mainwindow.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../src/mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all: qrc_chemvp.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_chemvp.cpp
qrc_chemvp.cpp: ../src/chemvp.qrc
	/Developer/Tools/Qt/rcc -name chemvp ../src/chemvp.qrc -o qrc_chemvp.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

