#############################################################################
# Makefile for building: cheMVP.app/Contents/MacOS/cheMVP
# Generated by qmake (2.01a) (Qt 4.4.0) on: Mon Jul 28 16:00:25 2008
# Project:  cheMVP.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.4/mkspecs/macx-g++ -macx -o Makefile cheMVP.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SVG_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O0 -g -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.4/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/Library/Frameworks/QtSvg.framework/Versions/4/Headers -I/usr/include/QtSvg -I/usr/include -I. -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtSvg -framework QtGui -framework Carbon -framework AppKit -framework QtCore -lz -lm -framework ApplicationServices
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.3

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       =  
OBJECTS       = 
DIST          = /usr/local/Qt4.4/mkspecs/common/unix.conf \
		/usr/local/Qt4.4/mkspecs/common/mac.conf \
		/usr/local/Qt4.4/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.4/mkspecs/qconfig.pri \
		/usr/local/Qt4.4/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.4/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.4/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.4/mkspecs/features/debug.prf \
		/usr/local/Qt4.4/mkspecs/features/default_post.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.4/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.4/mkspecs/features/qt.prf \
		/usr/local/Qt4.4/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.4/mkspecs/features/moc.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.4/mkspecs/features/resources.prf \
		/usr/local/Qt4.4/mkspecs/features/uic.prf \
		/usr/local/Qt4.4/mkspecs/features/yacc.prf \
		/usr/local/Qt4.4/mkspecs/features/lex.prf \
		cheMVP.pro
QMAKE_TARGET  = cheMVP
DESTDIR       = 
TARGET        = cheMVP.app/Contents/MacOS/cheMVP

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile cheMVP.app/Contents/PkgInfo cheMVP.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) cheMVP.app/Contents/MacOS/ || $(MKDIR) cheMVP.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cheMVP.pro  /usr/local/Qt4.4/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.4/mkspecs/common/unix.conf \
		/usr/local/Qt4.4/mkspecs/common/mac.conf \
		/usr/local/Qt4.4/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.4/mkspecs/qconfig.pri \
		/usr/local/Qt4.4/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.4/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.4/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.4/mkspecs/features/debug.prf \
		/usr/local/Qt4.4/mkspecs/features/default_post.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.4/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.4/mkspecs/features/qt.prf \
		/usr/local/Qt4.4/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.4/mkspecs/features/moc.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.4/mkspecs/features/resources.prf \
		/usr/local/Qt4.4/mkspecs/features/uic.prf \
		/usr/local/Qt4.4/mkspecs/features/yacc.prf \
		/usr/local/Qt4.4/mkspecs/features/lex.prf \
		/Library/Frameworks/QtSvg.framework/QtSvg.prl \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Qt4.4/mkspecs/macx-g++ -macx -o Makefile cheMVP.pro
/usr/local/Qt4.4/mkspecs/common/unix.conf:
/usr/local/Qt4.4/mkspecs/common/mac.conf:
/usr/local/Qt4.4/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.4/mkspecs/qconfig.pri:
/usr/local/Qt4.4/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.4/mkspecs/features/qt_config.prf:
/usr/local/Qt4.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.4/mkspecs/features/default_pre.prf:
/usr/local/Qt4.4/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.4/mkspecs/features/debug.prf:
/usr/local/Qt4.4/mkspecs/features/default_post.prf:
/usr/local/Qt4.4/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.4/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.4/mkspecs/features/warn_on.prf:
/usr/local/Qt4.4/mkspecs/features/qt.prf:
/usr/local/Qt4.4/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.4/mkspecs/features/moc.prf:
/usr/local/Qt4.4/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.4/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.4/mkspecs/features/resources.prf:
/usr/local/Qt4.4/mkspecs/features/uic.prf:
/usr/local/Qt4.4/mkspecs/features/yacc.prf:
/usr/local/Qt4.4/mkspecs/features/lex.prf:
/Library/Frameworks/QtSvg.framework/QtSvg.prl:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.4/mkspecs/macx-g++ -macx -o Makefile cheMVP.pro

cheMVP.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) cheMVP.app/Contents || $(MKDIR) cheMVP.app/Contents 
	@$(DEL_FILE) cheMVP.app/Contents/PkgInfo
	@echo "APPL????" >cheMVP.app/Contents/PkgInfo
cheMVP.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) cheMVP.app/Contents || $(MKDIR) cheMVP.app/Contents 
	@$(DEL_FILE) cheMVP.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,cheMVP,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.4/mkspecs/macx-g++/Info.plist.app >cheMVP.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/cheMVP1.0.0 || $(MKDIR) .tmp/cheMVP1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/cheMVP1.0.0/ && (cd `dirname .tmp/cheMVP1.0.0` && $(TAR) cheMVP1.0.0.tar cheMVP1.0.0 && $(COMPRESS) cheMVP1.0.0.tar) && $(MOVE) `dirname .tmp/cheMVP1.0.0`/cheMVP1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/cheMVP1.0.0


clean:compiler_clean 
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r cheMVP.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

