#!/usr/bin/ruby

# Ignore this for now...
FolderName = File.basename(Dir.getwd)
#FileName   = FolderName + ".pro"
# Just call everything chemvp
FileName   = "cheMVP.pro"

QMakeFile  = File.new(FileName, "w")
SourceArray = Dir["../src/*.{cc,cpp}"].reject{|f| f.match(/^moc_/) || f.match(/^qrc_/)}
ResourceArray = Dir["../src/*.{qrc}"]
QMakeFile.puts "SOURCES = " + SourceArray.join("  \\ \n")
QMakeFile.puts "HEADERS = " + Dir["../src/*.h"].join("  \\ \n")
if(ResourceArray.size)
    QMakeFile.puts "RESOURCES = " + ResourceArray.join("  \\ \n")
end
QMakeFile.puts "macx{\n  ICON = ../images/icon.icns\n}"
QMakeFile.puts "win32{\n RC_FILE = ../images/icon.rc\n}"
QMakeFile.puts "CONFIG += debug_and_release static"
QMakeFile.puts "macx{\n  CONFIG += ppc x86\n}"
QMakeFile.puts "win32{\n  CONFIG -= debug\n}"
QMakeFile.puts "QMAKE_CXXFLAGS_DEBUG = \" -O0 -g\""
QMakeFile.puts "QT += svg"
QMakeFile.close

if ENV["VENDOR"] == "apple"
     `qmake -spec macx-g++ #{FileName}`
else
     `qmake #{FileName}`
end
