#!/usr/bin/ruby

# Ignore this for now...
FolderName = File.basename(Dir.getwd)
#FileName   = FolderName + ".pro"
# Just call everything chemvp
FileName   = "cheMVP.pro"

QMakeFile  = File.new(FileName, "w")
SourceArray = Dir["../src/*.{cc,cpp}"].reject{|f| f.match(/^moc_/) || f.match(/^qrc_/)}
ResourceArray = Dir["../src/*.{qrc}"]
QMakeFile.puts "SOURCES = " + SourceArray.join("  \\ \n")
QMakeFile.puts "HEADERS = " + Dir["../src/*.h"].join("  \\ \n")
if(ResourceArray.size)
    QMakeFile.puts "RESOURCES = " + ResourceArray.join("  \\ \n")
end
QMakeFile.puts "CONFIG += release static"
QMakeFile.puts "QMAKE_CXXFLAGS_DEBUG = \" -O0 -g\""
QMakeFile.puts "QMAKE_LFLAGS += \" -static\""
QMakeFile.puts "QMAKE_LIBS += \"-L/usr/lib64 -lfreetype -lexpat -lSM /usr/lib64/gcc/x86_64-suse-linux/4.1.2/libstdc++.a \""
QMakeFile.puts "QT += svg"
QMakeFile.close

if ENV["VENDOR"] == "apple"
     `qmake -spec macx-g++ #{FileName}`
else
     `qmake #{FileName}`
end
