#!/usr/bin/ruby

# Ignore this for now...
FolderName = File.basename(Dir.getwd)
#FileName   = FolderName + ".pro"
# Just call everything chemvp
FileName   = "cheMVP.pro"

QMakeFile  = File.new(FileName, "w")
SourceArray = Dir["../src/*.{cc,cpp}"].reject{|f| f.match(/^moc_/) || f.match(/^qrc_/)}
ResourceArray = Dir["../src/*.{qrc}"]
QMakeFile.puts "SOURCES = " + SourceArray.join("  \\ \n")
QMakeFile.puts "HEADERS = " + Dir["../src/*.h"].join("  \\ \n")
if(ResourceArray.size)
    QMakeFile.puts "RESOURCES = " + ResourceArray.join("  \\ \n")
end
QMakeFile.puts "\nCONFIG += debug_and_release static"
QMakeFile.puts "QT += svg"
QMakeFile.puts "QMAKE_CXXFLAGS_DEBUG = \" -O0 -g\""
QMakeFile.puts "\nmacx{"
QMakeFile.puts "  ICON = ../images/icon.icns\n"
QMakeFile.puts "  CONFIG += x86\n"
QMakeFile.puts "}"
QMakeFile.puts "\nwin32{"
QMakeFile.puts "  RC_FILE = ../images/icon.rc"
QMakeFile.puts "  CONFIG -= debug"
QMakeFile.puts "  QMAKE_CXXFLAGS_RELEASE -= -mthreads"
QMakeFile.puts "  QMAKE_LFLAGS_RELEASE -= -mthreads"
QMakeFile.puts "}"
QMakeFile.close

`qmake -spec macx-g++ #{FileName}`
